### ISSUE TITLE
README-DEVELOPER.md needs expanding

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#100]
The documentation is incomplete and assumes the reader is familiar with these tools.

https://github.com/ucsb-wsg/ucsb-wsg.github.io/blob/master/README-DEVELOPER.md

For example, you must cd into the cloned repo to run npm install.

It also mentions installing Jekyll, which in itself is condescending in saying "just run gem install jekyll" as they must assume everyone has Ruby installed or even knows that gem is a ruby command. It takes a bit of digging to find the requirements.

The docs should point out all dependencies, like Ruby, a Git Client (assumed since you are on gitHub I guess)

Listing the full steps and defining all the required software will help in others cloning and testing the site.

**Comment by garster** [comment]
Guess we need "gulp" too.

**Comment by tenken** [comment]
@garster I believe the original goal of the developer documentation was not to empower any layperson attending the meeting to work on the project from a local test environment. But be additional notes for contributing campus developers.

If someone is unfamiliar with Ruby based development, or GithubPages than the existing documentation may seem somewhat lacking; for me as an example the documentation was not alltogether lacking -- I've done Ruby/Rails/Nanoc/Camping/Sinatra ... etc programming in the past. I'm familiar with the development stack.

I would caution how much extensive documentation we should maintain as in this case of Github altering the offered library stack (dropping BlueCloth and supporting only RedCloth as a Markdown flavor). Their requirements may be fluid.

Alot of the dependencies you described are documented in the Github Pages official documentation site found here:
https://pages.github.com/

The specific requirements of Ruby, Gulp and other libraries can be found within the above site here:
https://help.github.com/articles/using-jekyll-with-pages/

I don't believe Gulp is a hard requirement of the project -- but it's a tool used commonly now in the Ruby realm for automated tasks. By examining the build file a developer could issue all those commands by hand.

Since the Github Pages are powered by Jekyll largely, obviously, the Jekyll documentation would also be relevant. This is because Jekyll is a framework of which the a primary motto is convention over configuration. If a developer is new to the conventions, there can be growing pains.
https://jekyllrb.com/docs/home/

As an example I believe there's crazy dynamic things we could do with Front Matter -- but it wouldn't help ease of development of the project. But Front Matter and interacting with it is a convention of Jekyll.

I don't really see of value of attempting to document exact version numbers, due to the freedom Github has in altering the usable stack of choices we have. I do see value in linking the above resources into the developer guide somewhere.

**EDIT**

Exact version numbers of Jekyll and other Github Pages libraries may be found at:
https://pages.github.com/versions/

And a tool to install all the above dependencies is the `github-pages` gem as described at the bottom of the versions page.

**Comment by loganfranken** [comment]
The general consensus from the group today was that there is a desire to have more information for new developers getting started on this project (i.e. where and how to install dependencies).

To that end, I think this issue should be reopened.
