### ISSUE TITLE
About Calendar is shows no meetings

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#117]
The calendar embeds ok, but shows no entries for any monthly WSG meeting in 2016:
http://webguide.ucsb.edu/about/

**EDIT**
The error is:
`Events from one or more calendars could not be shown here because you do not have the permission to view them.`

**Comment by garster** [comment]
I tried it in different browsers logging and in  not logged in and I got different results. For example in Chrome, not logged in I saw a empty white space. In Edge I got a "this content is blocked" and I think it is related to the HTTPS calendar embedded in an HTTP Site.

I am going to remove it because it does not work well.

**Comment by tenken** [comment]
Can you try HTTP for now?

**Comment by tenken** [comment]
Can you try HTTP for now? GhPages doesn't support SSL (yet) I think. We could try protocol less URL so that if HTTP does work, then we don't need to edit the URL once SSL is enabled on the site... Hehe I think the webguide says no protocol less url usage.

**Comment by tenken** [comment]
Related SSL for Github Pages historical summary:
https://gist.github.com/coolaj86/e07d42f5961c68fc1fc8

You can vote for SSL on ghpages here:
https://github.com/isaacs/github/issues/156
