### ISSUE TITLE
Consider Removing IE10 Viewport Bug Fix

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#144]
Per suggestion in #140, consider removing IE10 viewport bug fix.

**Comment by ericmayes** [comment]
[Internet Explorer 10 in Windows 8 and Windows Phone 8](http://getbootstrap.com/getting-started/#support-ie10-width)

Internet Explorer 10 doesn't differentiate device width from viewport width, and thus doesn't properly apply the media queries in Bootstrap's CSS. Normally you'd just add a quick snippet of CSS to fix this

`@-ms-viewport       { width: device-width; }`

However, this doesn't work for devices running Windows Phone 8 versions older than Update 3 (a.k.a. GDR3), as it causes such devices to show a mostly desktop view instead of narrow "phone" view. To address this, you'll need to include the fix CSS and JavaScript to work around the bug. Source can be seen in the link above.

**Comment by tenken** [comment]
I wasn't necessarily against keeping or removing this, but merely documenting why it was there (if it was a purposeful Bootstrap include, or something by the designer/developer).

I looked at the Merge Commit changelist and saw `ie10-viewport-bug-*` files and as an outsider or contributor to the project, not _knowing_ the latest bootstrap internals -- this is an example of something which additional documentation would be great to cover to aide other community contributors.

Along the same lines, http://getbootstrap.com/getting-started/#support-safari-percentages, might be 1 reason (as Logan mentioned previously) that so many significant digits are used in the CSS file for percentage units. Documenting this could help new contributors not choose _their_ conventions over these and overwrite the .33333 with .3 for example.

Thanks! @ericmayes

**Comment by loganfranken** [comment]
Alright, it sounds like there's reason to keep the fix, but we may want to jot a note about it down somewhere in the wiki?
