### ISSUE TITLE
Webguide styling - how closely should it track the ucsb.edu styling?

### ISSUE THREAD

**Issue by fablio-work** [UCSantaBarbara/webguide#21]
This is a "branding" issue that was brought up at the May 2015 WSG meeting.

How closely should the webguide styling track with the ucsb.edu site styling?
### Background/History

Historically, the webguide has matched the styling and look and feel of the ucsb.edu website.
The thought has been that the matching branding adds "credibility/legitimacy" to the webguide.

During the last major webguide update, the subcommittee made a strategic and informed choice to break away from some of the out-of-date styling of the ucsb.edu site (image based nav links, non-web based fonts) to make the site more accessible, but still maintain a very similar look-and-feel.

The ucsb.edu will be undergoing a major styling update in the coming months.  The site is also slated to be migrated to a CMS sometime within the next three years (or so?).

**Comment by loganfranken** [comment]
Were there arguments discussed for why it _shouldn't_ track the new design?

During the last update, we broke away from some of the dated elements, but I felt we kept the same general look-and-feel of the main website.

So, to that end, I feel like there's two scenarios:
- We decide to _not_ follow ucsb.edu styling, in which case our Web Guide will look like the _old_ ucsb.edu and we will probably want to freshen up the design some time soon
- We _do_ decide to track ucsb.edu styling, in which case we need to update the guide to fit the new look

I feel like either way we end with a redesign, so why not skip the design work and just update the styling to match the refreshed ucsb.edu?

**Comment by tenken** [comment]
> Were there arguments discussed for why it shouldn't track the new design?

Basically I'm making the argument. I understand the webguide has historically looked similar to the main ucsb site. An individual suggested that it should outside of the wsg meeting and I disagreed with them.

The wsg is a guiding force on standards. If the ucsb main page is standards compliant there is no reason the webguide can be standards compliant yet appear different on the surface. My ultimate example of this is http://www.csszengarden.com/  wherein the HTML is the same -- yet every "theme" on the right side of the page is different CSS.

Also, the webguide is usually themed by 1 designer in every iteration of the previous designs -- I want that designer to have whatever freedom they want to express themselves fully in this work; rather than being mandated to create something "similar" to the live ucsb site simply because.

> I feel like either way we end with a redesign, so why not skip the design work and just update the styling to match the refreshed ucsb.edu?

I'm open to any outcome. I did want to get your feedback on the matter. And I said we'd have an open vote at the next June 2015 meeting regarding which design path we take with the WSG guide in its next thematic revision.

**Comment by loganfranken** [comment]
Thanks for the info!

To be clear: I'm cool with either direction; tracking ucsb.edu just seemed like less work. But a fresh design specific to the web guide itself could be cool too!

**Comment by garster** [comment]
My 2 cents: The the look and feel, navigation, etc should be that of ucsb.edu, only the content should be what we are concerned with here. How that integrates into the ucsb.edu site is a technical issue to work out, especially after they move to a CMS. 

I base this on the fact it is a sub-directory of ucsb.edu. If it were a separate site then I would suggest its own styling.

**Comment by loganfranken** [comment]
During the meeting today, the group decided that the guide should track the styling of ucsb.edu (or, work closely with Public Affairs if we want to have a different look-and-feel), _especially_ if the guide will be a subdirectory of ucsb.edu.

**Comment by loganfranken** [comment]
I think this was just a discussion topic (and not a specific implementation issue), so I think we can actually close this?

**Comment by UCEAP-JCOLON** [comment]
I think we should close this. Seems like most support leans to closely follow UCSB style guidelines.

**Comment by tenken** [comment]
sure feel free to close it James. Thanks!

**Comment by UCEAP-JCOLON** [comment]
Closing per consensus.
