### ISSUE TITLE
Verify Scripts Are Still Blocking Resources

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#220]
I would like to verify that scripts are still a "blocking resource" that should be included before the end of the body tag:
http://webguide.ucsb.edu/resources/

**Comment by garster** [comment]
Everything I hear says they are executed in order as they are loaded. I think this behavior will forever be in browsers since load order is expected by so many.

But also this recommendation should be modified because depending on how the author wrote the JS code, it might need to be at the top.

I am interested. I might run some tests myself using breakpoints in the JS to see what loads.

**Comment by garster** [comment]
Mozilla talks about reducing the use of inline scripts and to optimally order the components on [Tips for authoring fast-loading HTML pages](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages).

**Comment by loganfranken** [comment]
Based on some research, this still appears to be true:
https://developers.google.com/speed/docs/insights/BlockingJS

We'll want to update these recommendations to suggest using some combination of the "async" or "defer" keywords at some point (rather than plopping the scripts right before the closing body tag), but the current recommendations are still valid.
