### ISSUE TITLE
Anchors on page make content hide behind header.

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#275]
When on a page like http://webguide.ucsb.edu/footer/

Click on something like 'privacy notification'

See the page jump down, but the top of the content is hidden.

This is due to the nav being separate in the dom, so the anchor does not take that into account. There are hacks to get it to work right.

**Comment by loganfranken** [comment]
Dang, this one's tricky.

I tried this CSS-only approach but it didn't work for me:
https://css-tricks.com/hash-tag-links-padding/

I also tried to hack this in w/ JS and it worked for the jump links but I couldn't get it to work when a user comes to the page initially (I think because the menu is jumping around when the script fires). I also don't love the idea of jumping through hoops to implement native browser behavior in JS.

```js
function fixAnchorLinks()
{
  $('a[href^="#"]').on('click', function(evt) {

    var $this = $(this);
    var id = $this.attr('href');

    var success = scrollToAnchor(id);

    if(success)
    {
      evt.preventDefault();
      history.pushState(null, null, id);
    }

  });
}

function handleUrlAnchor()
{
  if(window.location.hash)
  {
    scrollToAnchor(window.location.hash);
  }
}

function scrollToAnchor(anchorId)
{
  var $target = $(anchorId);

  if($target.length === 0)
  {
    return false;
  }

  var offset = 45;

  if($('#webguide-li').hasClass('open'))
  {
    offset = 330;
  }

  $('html, body').scrollTop($target.offset().top - offset);

  return true;
}

// starting the script on page load
$(function() {
  fixAnchorLinks();
  handleUrlAnchor();
});
```

I'll come back to this but I'm posting this here in case someone has other ideas? Or can see what I'm doing wrong?

**Comment by loganfranken** [comment]
Alright, the CSS Tricks fix works if you swap the padding for margins on the H3:

```css
h3
{
  margin: 7px 0 5px 0;
  padding: 0;
}

h3::before
{
  display: block;
  content: " ";
  margin-top: -50px;
  height: 50px;
  visibility: hidden;
}
```

This is a lot cleaner but it still doesn't work when the page first loads due to the menu shifting.

**Comment by loganfranken** [comment]
Weird! I tested that solution again this morning and it works just fine on first load. Submitting the PR
