### ISSUE TITLE
W3C validation warning: The navigation role is unnecessary for element nav.

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#276]
Related to #237 

Warning: The navigation role is unnecessary for element nav.
From line 86, column 9; to line 86, column 78
<nav class="collapse navbar-collapse" role="navigation" id="ucsb-nav">

**Comment by ericmayes** [comment]
I guess the thought is that since legacy IE support is no longer needed for html5 semantic elements, neither are these ARIA landmark roles? Even IE 11 only lists partial support but that's only because the <main> element isn't fully supported. These ARIA roles do cause validation warnings but not errors to my understanding. 

It really isn't about IE recognizing the <nav> element which its been able to do for a long time via the HTML5 Shiv. This is about the Accessibility API understanding the semantics of <nav>. Screen Readers use landmark roles to make it easier for users to jump to different areas.

I also found this: 
"According to http://html5accessibility.com/, Internet Explorer has not mapped the <nav> semantics to the Windows' accessibility API. As far as I can tell from related IE bug reports, it affects all version of IE, and Edge too."
