### ISSUE TITLE
Consider Adding Topic: How to Use Copyrighted Images

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#287]
See #265

**Comment by loganfranken** [comment]
I don't personally have any ideas for what to add for this topic:

We've got links to UCSB images on the "Campus Resources" page (http://webguide.ucsb.edu/campus-resources/#ucsb-campus-image-resources) and I think each of those individual resources likely has guidelines on how to use their images.

On top of that, we've got guidelines on using images of people and getting photo releases (http://webguide.ucsb.edu/policies/#use-of-images-and-photo-releases).

So I think this would be the general topic of how to use copyrighted images, which would require us to provide a primer on fair use, etc., which feels out of scope for us.

I would vote to close this ticket unless anyone has any other ideas on how to approach this topic? (Or maybe if you disagree with my assertions above too!)

**Comment by loganfranken** [comment]
Any thoughts on this?

**Comment by ghost** [comment]
Since copyrighted assets can come from a variety of sources and use different terms of use is I find that each issue is usually unique. i.e creative commons, nasa, getty images etc. A  best practice is to have a digital or print copy of the terms, image and URL for future reference for your project.

If we do add a topic it should just be about keeping records...

**Comment by dsaludares** [comment]
I vote that we close this issue as well.  Even a guide on how to keep records of copyrighted images, while helpful, is outside the scope of the web guide.

**Comment by loganfranken** [comment]
I'll mark this topic as closed, but feel free to reopen for discussion at a WSG meeting!
