### ISSUE TITLE
Consider Adding Topic: Form design

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#290]
See #265

**Comment by loganfranken** [comment]
I think this topic sounds like a good addition, but I don't really have any ideas for it. Anyone else?

**Comment by loganfranken** [comment]
Unless anyone has specific ideas for this one, I vote to close it. (But I'm open to what everyone else thinks!)

**Comment by garster** [comment]
For me I have problems with bad form design and don't see anything on the webguide about it. There is a trend to not use labels on fields and to just use placeholders. Once there is data in the field you can no longer see what the field is for. This less-usable design especially for someone like me that use Chrome autofill to populate name, address, etc. The autofill will sometimes not correctly fill. If there is no label I cannot tell if Chrome but the correct data in. I don't know the implications for a blind or partially sighted person is, but I can imagine the lack of an aria-label or the low-contrast placeholder text being an issue.

It might be 'opinionated' but I think we can spell out some good form design suggestions to make things more usable.

Goals
1. Easy to use with keyboard only
2. Easy to identify fields
3. Fields that fit the content
4. Appropriate feedback on limits and errors.

Some ways to accomplish those goals
1. Labels on every field
2. Labels properly linked to field with markup
3. Proper label markup for Checkboxes/radio buttons {I would like some research on that because I still don't know}
4. Text counters on textareas
5. Width of fields should match expected content. I've seen many dropdowns where I could not see the values.
6. Match fields to expected data type. Example: Credit card expiration month. On the cards it is always numbers, but I've seen dropdowns that spell out the month so I have to THINK which month is "04". Also see crazy limits on field like Email Address: "Cannot be longer than 50chars" when the email spec is 254 chars.

I could go on and on about bad form design but I think a curated list of bad/good would be great. Not UCSB specific like colors and footers, but still good info in one place.

**Comment by loganfranken** [comment]
Created a wiki page to start drafting out the text for this section:
https://github.com/UCSantaBarbara/webguide/wiki/Form-Design

**Comment by loganfranken** [comment]
Moving the content from the wiki page here and deleting the page:

## Sorted Content

### Forms HTML Guidance

(Can be added here: https://webguide.ucsb.edu/html/#forms)

* Guidance on use of placeholders as labels or how to label without using a label
* Warning on the low contrast of placeholder text against input text box?
* Fields that fit the content (e.g. input size) (i.e. Width of fields should match expected content)
* Appropriate feedback on limits and errors
* Text counters on textareas 
* Match fields to expected data type (Example: Credit card expiration month. On the cards it is always numbers, but I've seen dropdowns that spell out the month so I have to THINK which month is "04". Also see crazy limits on field like Email Address: "Cannot be longer than 50chars" when the email spec is 254 chars.

### Field Visual Guidance

(Can be added here: https://webguide.ucsb.edu/css/#display)

* Easy to identify fields

### Checkbox/Radio Button Labels

(Can be added here: https://webguide.ucsb.edu/html/#forms)

* Proper label markup for Checkboxes/radio buttons

### Duplicate Content

* Easy to use with keyboard only (https://webguide.ucsb.edu/web-accessibility/)
* Labels on every field (https://webguide.ucsb.edu/html/#forms)
* Labels properly linked to field with markup (https://webguide.ucsb.edu/html/#forms)
