### ISSUE TITLE
Consider Adding Topic: Cloud Hosting/Storage Recommendations

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#298]
See #265

**Comment by tenken** [comment]
I vote we close this topic as outside the current focus of the guide.

Or that we re-label this as best practices in how to use the campus based Cloud Storage providers with existing web frameworks and CMSs. For example I have asked clients to provide periodically updated resources in a UCSB Box folder and to share out the folder to the public, and embedding that share link into Drupal as-needed, rather than attempting to manage resource files from within a CMS for the campus or public consumption.

**Comment by loganfranken** [comment]
I don't have a strong opinion on this one, although I think it might need to morph (as @tenken says) into a discussion on Drupal hosting options or how resources should be hosted on the cloud in relation to Drupal sites.

**Comment by dsaludares** [comment]
It sounds like this should be 2 separate issues:

1. Website cloud hosting (e.g., Pantheon for Drupal and WordPress, Acquia for Drupal, etc.)
2. Best practices for sharing information posted on websites using cloud services (e.g., Box or Google Drive)

What do you think?

**Comment by loganfranken** [comment]
I personally think it makes sense to point people to resources for 1, but I'm not sure we could put together consistent standards for 2?

For example, in FinAid we don't mind staff managing resources like PDFs in the CMS, although we encourage them to host videos on YouTube; that feels like an arbitrary decision specific to what works best for our department. (Although maybe I'm wrong and everyone follows similar standards?)

As always, I'm open to what you all think is best, though!

**Comment by dsaludares** [comment]
You're right about 2, @loganfranken. Most Drupal sites in the Division of Admin Services manage resources in the CMS. For a couple of the Drupal sites I manage for ETS, the content editors occasionally point to Box links. I guess it is more like "options" instead of "best practices."

**Comment by ghost** [comment]
Topic closed per discussion in April 3 meeting. Outside current focus of guide.
