### ISSUE TITLE
Clearfixing

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#32]
Another one from the _History Books of CSS_:

I'm wondering if we should include some advice on **clearfixing**?

For those unfamiliar, if you have a parent element with floated children inside, the parent won't contain them.

In other words, this:

``` html
<div style="border: 3px solid #000;">
  <div style="float: left;">Left Content</div>
  <div style="float: right;">Right Content</div>
</div>
```

Results in this:

![uncleared](https://cloud.githubusercontent.com/assets/1024444/7889596/5c185ed2-05f5-11e5-9f4c-a96f726c143c.png)

For the longest time, it was common practice to fix this by just inserting a utility element with `clear: both` applied to it.

``` html
<div style="border: 3px solid #000;">
  <div style="float: left;">Left Content</div>
  <div style="float: right;">Right Content</div>
  <div style="clear: both"></div>
</div>
```

I actually stuck with this method for a long time until I discovered that applying `overflow: auto` or `overflow: hidden` to the parent element works just as well.

For more complex cases, there are clearfixes like the [micro clearfix hack](http://nicolasgallagher.com/micro-clearfix-hack/).

Sitepoint did a pretty great [rundown of the various methods](http://www.sitepoint.com/clearing-floats-overview-different-clearfix-methods/) and I threw together a [demo](http://codepen.io/loganfranken/pen/aOpwOq) demonstrating the various techniques as well.

Since this is a fairly common use case (at least in my experience), I'm wondering if we should include some guidance within the web guide.

Any thoughts? Opinions?

**Comment by tenken** [comment]
I don't typically see

```
<div style="clear: both"></div>
```

used alot anymore with the advent of CSS frameworks to build upon. Moreso, with the examples of Flexbox given recently in the WSG meetings.

I would be of the opinion -- the sooner it dies (and how can I help it die) then all the better. That being said I say we don't mention it. More to the point I might argue we should have a "top 5" used CSS frameworks on campus this year. While we're here to advocate to standards I don't necessarily agree everything should be created from scratch -- which is a broad sense is being advocated here.

Eg, http://stackoverflow.com/questions/14973317/understanding-bootstraps-clearfix-function

The approach you've outlined is a trivial implementation of boostrap's .clearfix. Yet to be more far-reaching and backwards compatibles FB's is about 1000's more cryptic; yet remains consistent in old browsers. Which is why I mention offering a rundown of modern CSS frameworks (or even just links to useful CSS frameworks).

Kinda annoying builtwith.com doesn't show CSS framework usage ... http://builtwith.com/webguide.ucsb.edu

If builtwith.com had a CSS usage metric it would have been an interesting task to run some analytics on the campus CSS (framework) usage.

**Comment by loganfranken** [comment]
I agree with you @tenken on both fronts: (1) let's not provide guidance on this and (2) let's discuss possibly providing guidance on front-end frameworks.
