### ISSUE TITLE
Change external links to HTTPS where possible.

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#39]
Many sites have HTTPS enabled. Some will redirect HTTP to HTTPS. We should be proactive and look for all HTTP links and update them to HTTPS if the remote site has it enabled.

On a side note. HTTPS is going to get real cheap and easy real soon https://letsencrypt.org/

**Comment by ericmayes** [comment]
the links should be changed to exclude http context for example <a href="//www.ucsb.edu"></a>

**Comment by loganfranken** [comment]
I'm all for this!

**Comment by fablio-work** [comment]
I think it's worth mentioning.  

I have noticed that more and more sites are starting to direct connections through https, but had not heard of the [http://letsencrypt.org](http://letsencrypt.org) push until now though.   Switching to HTTPS creates some minor performance impacts:
- latency - some extra roundtrips to negotiate the TLS connection
- processing - encryption/decryption (server/client)
- bandwidth - the payload size is increased

The following writeup seems to to cover that topic well: http://serverfault.com/questions/570387/https-overhead-compared-to-http.  The authors bottom line:  the impact is negligible.

Obviously, users with slower connections will be impacted more, but not sure how obvious those impacts would be.

Regardless, more and more sites are beginning to take the approach of encrypting rather than trying to keep track of what should or shouldn't be encrypted (ie: just playing it safe).  And I don't know that there is anything wrong with that.  

I think it's worth addressing the topic in the webguide :-)
