### ISSUE TITLE
add Accessibility page for Sitemimprove "Nextgen" update

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#417]
Add a note/section to Siteimprove page regarding Nextgen update at https://webguide.ucsb.edu/accessibility/siteimprove

**Comment by tenken** [comment]
08-02-2021
* Questions for Eric regarding new Siteimprove features with Webguide site updates, any site impacts with crawling from next-gen service and Pantheon.
* Is this verbiage enough: https://webguide.ucsb.edu/accessibility/siteimprove
* https://webguide.ucsb.edu/accessibility-0

**Comment by ericmayes** [comment]
We probably don't need to speak to next gen specifically in the guide unless we want to mention how a slight change in accessibility score may be noticed since the upgrade, and how the history of the previous gen accessibility score is still stored to maintain our past comparison of scores. But we probably don't need to do this since it doesn't affect how people use the tool much. I will give a training at some point to go over what the changes were and also to mention the new process to scan password protected sites. This is another new major feature. We will have to develop what the channels are for security approval at UCSB for this. Basically only sites with non confidential information are allowed, but past that there should still be some official security approval in each case. Hopefully it won't be needed very much and the chrome extension can be used to test these kind of sites. For now we might want to link to UCOP's resources on this : [Checking websites](https://www.ucop.edu/electronic-accessibility/web-developers/tools-and-testing/siteimprove/index.html) and [Checking non-public-facing sites](https://www.ucop.edu/electronic-accessibility/web-developers/tools-and-testing/siteimprove/non-public-websites.html)
