### ISSUE TITLE
Responsive Image Recommendations

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#71]
During the meeting today, we talked about how the logo on the redesigned UCSB website looks blurry on high-resolution displays.

@ericmayes and I provided a number of solutions (let me know if I missed anything, @ericmayes):
- Use SVG
- Use a font with a similar style as the logo
- [Doubling the size of an image and scaling it down](https://www.filamentgroup.com/lab/compressive-images.html)
- Use the [`sizes` and `srcset` attributes and the `picture` element](https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content)
- Use the polyfill for [`sizes`, `srcset`, and `picture`](https://github.com/scottjehl/picturefill)

I think the last two should be the recommended way to go, unless SVG can be used instead.

These are recommendations for fixing the logo on the newly redesigned page, but we may want to move these recommendations into the guide/wiki.

**Comment by loganfranken** [comment]
I went on a walk during lunch and I realized I shouldn't have implied the use of `picture` (or its polyfill) would be the ideal option in this specific case.

For the case of the logo, I think @ericmayes's suggestion of SVG should be considered the most ideal choice, specifically since you'll probably have vector data easily accessible for a logo.

For more complex images, `picture` would likely be the recommended way to go.

**Comment by ericmayes** [comment]
Thanks for summarizing all this @loganfranken! You are correct, The UC Santa Barbara logo is an ideal candidate for the SVG format. Its only IE8 where SVG isn't supported but an img fallback could be loaded in [a number of different ways](http://callmenick.com/post/svg-fallback-with-png), one newer method ironically being with the [picture element](http://sarasoueidan.com/blog/svg-picture/) itself - requiring the need for the picture polyfill. Of course if you look at the new UCSB.edu site in IE8 a message comes up warning you that your browser is out of date and you should upgrade (nicely done!). So perhaps the image fallback isn't needed, but I do know there are still some machines running IE8 on campus (for instance Recreation Center). But if the polyfill was used, it would also benefit loading time for the larger photographs that load on the page.

The one I was thinking of is [Picturefill.js](http://scottjehl.github.io/picturefill/). An example of a site using this approach for their large photos is  www.chapman.edu. Picturefill.js is available in two flavors: Version 2, which mimics the approach used by the yet fully supported <picture> element, and Version 1, which uses <span> elements and custom data attributes to accomplish the same behavior. I haven’t implemented this yet, it was just something I researched for the Economic Forecast Project website. One of the big reasons is how multiple image sets might be able to work with a CMS image manager. Its putting too much on the user to expect them to be able to upload multiple versions of an image, let alone finding a high res image to start with that supports retina.

Although I totally prefer SVG, before the picture polyfill came out, and to keep supporting IE8, we decided to load an additional retina image for departmental logos in Student Affairs using a media query like the following. This isn't the best approach since it sacrifices some loading time to load the additional image, but we have found it works fairly well. Figured I would share that method too:

```
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
      #ucsb-answers #ucsb-answers-image {
        /* Retina */
        background: url("../images/ucsb-answers@2x.png") 100% auto; }
}
```

Also wanted to mention an easy way to see how your page might look on a retina display is to zoom in at 200% using your browser. This will give you an idea of what the images will look like

**Comment by tenken** [comment]
Awesome Info thanks guys! Should items like this go to the Wiki, or perhaps always add a useful label such as "hot tips" and provide a link in the Wiki or Webguide to the issue queue for "hot tips" that have been closed?

I'm basically asking how can we best make neat tips like this more accessible to the general public without necessarily trying to keep a (book/webguide) up to date with them ... :D

**Comment by loganfranken** [comment]
Linking to the issues themselves works, but I personally like the approach of summarizing in the wiki/guide with a reference back to this issue.

I'm totally up for whatever the group thinks is best, though.

**Comment by loganfranken** [comment]
I summarized this discussion here:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Responsive-Images

Closing this issue for now, but please feel free to reopen or edit my work!

**Comment by tenken** [comment]
@loganfranken should the HTML5 Picture element be removed from this page now that this documentation is written?

https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Future-Areas-of-Development

**Comment by loganfranken** [comment]
Yeah, sounds good to me; I went ahead and removed it.
