### ISSUE TITLE
Front-end Framework Suggestions

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#72]
This was suggested by @tenken in #32:

Should we provide guidance on which front-end frameworks (e.g. Twitter Bootstrap or Zurb Foundation) are commonly used for campus websites?

**Comment by tenken** [comment]
I like this idea assuming a modern CMS (Drupal, WP, SiteFinity) or Framework (Rails, Symfony, etc) is being used ... there _tends_ to be boilerplate themes that integrate the big-boy CSS frameworks seamlessly into a theme for you out of the box. Some Drupal Examples:
- https://www.drupal.org/project/bootstrap
- https://www.drupal.org/project/zurb_foundation
- https://www.drupal.org/project/omega

Offhand I'm not sure what's typically used on campus. I know Ocean O Graphics historically uses AdaptiveTheme for drupal, and more recently Bootstrap.

**Comment by garster** [comment]
In my opinion: No.
- Frameworks change all the item, next week a new one will be popular.
- Frameworks are basically programs. This would be like suggesting a specific Word Process or Web Browser.

I would suggest we suggest people look into using some framework, because they will do a lot of the heavy lifting for you. But I would not recommend a specific one, as that is really a preference.

**Comment by tenken** [comment]
@garster I guess the argument could be that of allll the many CSS frameworks available. Here are the ones in-use by (seasoned) campus staff and attendees of the WSG :D. Meaning that these have been vetted, or are already in use due to their popularity and feature-set available out-of-the-box.

Of course over time the landscape of CSS frameworks would change and evolve.

I think a mile-high view of the (current trending) css frameworks known to be of use on campus could be useful for the campus at large. We  could emphasis that all these frameworks strive to provide groundwork or a toolbox that is accessible and feature-full from the get go.

As an example I'm not sure if SASS or LESS, or Bootstrapped is used heavily by student affairs, or more specifically SiteFinity on campus. I would also argue that using such tools is to provide a set of (framework) conventions to developed against -- when existing UCSB staff leave their position new staff would just need to know Bootstrap and not need to learn 1 developers point-of-view on how to code. Rather they learn the "industry best-practices" outlined and provided by the framework.

ps. i went overboard on my hyphenations. :P

**Comment by loganfranken** [comment]
Good points from the both of you!

Could we tag this for discussion tomorrow?

**Comment by ilessing** [comment]
I'm currently a fan of the [Pure CSS](http://purecss.io) framework.
What will be my favorite front end framework next week?
  Someday we're going to lose a developer to the Framework quicksand pool.  The dev will venture in and never emerge.

**Comment by loganfranken** [comment]
Today, the group decided to provide just a general note somewhere in the guide that explains the following:
- What these front-end frameworks are and what they do
- How they can be useful to ease and speed up development
- Examples of popular frameworks
- A note that these frameworks are constantly changing

Additionally, it was suggested that we should include testimonials from campus developers who have used specific frameworks.
