### ISSUE TITLE
Verify Jekyll Upgrade

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#97]
Looks like GitHub Pages updated Jekyll:
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

Doesn't seem like there are any breaking changes but it probably wouldn't hurt to (1) make super sure and (2) see if there are any features we should be using that we aren't using.

**Comment by loganfranken** [comment]
:sweat_smile: Phew! Looks like it didn't break anything!

**Comment by garster** [comment]
@loganfranken ya I did not know how to test it, so I trusted your good judgement on the PR.

**Comment by tenken** [comment]
@garster I believe the way to test would be to fork it to your local box. Assure you have the necessary dependencies to build the project (Gulp, and other Ruby gems I assume) and then attempt to build it out essentially.

Since they changed the markdown flavor, either we'd notice broken links or unsupported transformations in the live site -- or the compilation step of your local build would essentially fail or barf errors out.

**Edit**
This process is described in the README-DEVELOPER.md file
https://github.com/ucsb-wsg/ucsb-wsg.github.io/blob/master/README-DEVELOPER.md

Perhaps we should add verbiage to the Developer Docs such as:
- describe that due to Github changes such as on X update recently, it's recommend to build the site locally on occassion and inspect for build errors?
- other GUI ways exist to simply edit the Markdown and simple file changes with the Github web ui.
- Alternatively use git via CLI and develop on the site in a local testing instance of the site.

**Comment by loganfranken** [comment]
I might be mistaken, but I actually think this is a fairly tricky issue (that's why I was worried about it):

You can definitely test whether or not the given combination of Jekyll plugins/parsers works on your machine but, as far as I know, there is no definitive way to know if it will work once it gets up to GitHub since you can't completely replicate their set-up (AFAIK).

**Comment by tenken** [comment]
@loganfranken No I think you're right although that can be said for any toolchain between systems. And there is no "test framework" to assure future releases of the site don't break provided by Github or maintained by us (eg, we could provide directions for image based analysis of the generated content, but what a PITA).

That's why I simply recommend the most thorough form of inspecting the site is to essentially build out the content locally in a developer environment. If problems exist across system, with similar pinned versions of dependencies something else is at play (imho) outside of the framework.

Full disclosure, I early-on built the site locally for changes and then pushed them. But for simple Markdown edits I typically just fork in the github gui and do the edits in the online markdown editor -- it's so much quicker.

**Comment by loganfranken** [comment]
Yeah, sorry, to be clear: I totally agree w/ your testing approach. And it definitely might help to note it somewhere, as you suggested.

(I just needed some place to share my struggle w/ the fact that I realized I couldn't actually be sure it wouldn't break on pushing to GitHub :smile:)
